### ISSUE TITLE
[Bug] Crash on startup

### ISSUE THREAD

**Issue by ghost** [Jab125/goblin-traders-fabric#30] opened 2021-12-13 20:37 UTC
### Minecraft Username

Cavayero

### Version

latest commit

### Minecraft Version

1.16.*

### What did you expect?

Release a fix, thanks.

### What did you get?

crash on startup on serverside:
logs: https://pastebin.com/u5K43Jcs

**Comment by 3e2j** [comment] 2021-12-14 16:34
The problem is that this is on 1.16, we've had some server issues appearing on the 1.16 versions reported before. The biggest problem is that 1.16 was a port of 1.17's version that Jab ported for fun as an experiment, not expecting that a large playerbase would download it. Only 400 people out of the tens of thousands that download the newer versions use the 1.16 edition, so honestly I don't personally know if we'll be bothered enough to fix it as it works on single-player (servers in 1.16 aren't common anymore).
I'll have @Jab125 look into this issue but as far as I know _we don't support the 1.16 version anymore as it's too far outdated for what fabric is_.

I'll leave Jab to close this issue.

**Comment by Jab125** [comment] 2021-12-30 06:04
pushing aside as the 1.16 port was a one time thing like Mojang's April Fools updates

**Closed as completed by Jab125** 2021-12-30 06:04 UTC
Labels: bug, triage
